apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: test-runner

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

secretGenerator:
  - name: test-runner-config
    envs:
      - test-runner.env
